image: golang:1.23

stages:
  - build
  - docker_build
  - deploy

variables:
  GOPATH: /go
  IMAGE_NAME: registry.gitlab.com/map-routes/go-server
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA # Тег = хеш коммита

build:
  stage: build
  script:
    # - go test ./...
    - go build -o main ./cmd
  artifacts:
    paths:
      - main
    expire_in: 1 hour
  only:
    - main
docker_build:
  stage: docker_build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - echo $IMAGE_NAME
    - echo $CI_REGISTRY
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh  # Создаем директорию
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "Host *" > ~/.ssh/config
    - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
  script:
    - ssh -p 2224 safwood@193.38.235.180 "
      /usr/bin/docker pull $IMAGE_NAME:$IMAGE_TAG &&
      /usr/bin/docker stop map-routes || true &&
      /usr/bin/docker rm map-routes || true &&
      /usr/bin/docker run -d \
        --name map-routes \
        --restart=always \
        -p 8000:8000 \
        $IMAGE_NAME:$IMAGE_TAG
      "
  only:
    - main
